name: Equalizer999 Organization CI

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  fetch_data:
    uses: equalizer999-sandbox-playground/cicd-common/.github/workflows/rewf-with-output.yml@main

  post_result:
    runs-on: ubuntu-latest
    needs: fetch_data
    steps:
      - run: echo ${{ needs.fetch_data.outputs.firstword }} ${{ needs.fetch_data.outputs.secondword }}
